name: crc_terraform_frontend
on:
  push:
    branches:
      - "test"
permissions:
  id-token: write
  contents: write
  
jobs:
  Refresh_Index:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./src/Website/IndexBuilder
    
    steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with: 
            role-to-assume: arn:aws:iam::053127563287:role/GithubActionsRole
            aws-region: ca-central-1
#Checkout git repository for pipeline run
        - name: checkout
          uses: actions/checkout@v2
        
        - name: Run Indexbuilder Python
          run: python3 IndexBuilder.py

  Tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: ./src
    
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          role-to-assume: arn:aws:iam::053127563287:role/GithubActionsRole
          aws-region: ca-central-1
#Checkout git repository for pipeline run
      - name: checkout
        uses: actions/checkout@v2

#Install Terraform on runner vm
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.4
      
 #Update tf state data     
      - name: Terraform Init
        working-directory: ./src/terraform
        id: Init
        run: terraform init
      
      - name: Select Terraform Test Workspace
        working-directory: ./src/terraform
        run: terraform workspace select test
#Plan out steps to be applied with terraform
      - name: Terraform Plan
        working-directory: ./src/terraform
        id: Plan
        run: terraform plan -var-file="test.tfvars"

  Main_Branch_Pull_Request:
    permissions:
      pull-requests: write
    needs: Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./
        
#Final step to approve for prod
    steps:
      - name: Create Pull request
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh pr create --head "test" --base "main" --title "Merge Tested Changes into Main Repository" --body "Deploying to production" --repo "tim-grieve/CloudResumeWebsite"
      
      - name: Approve Pull request
        env:
          GITHUB_TOKEN: ${{ secrets.PULL_APPROVER }}
        run: gh pr review test --repo "tim-grieve/CloudResumeWebsite" --approve

      - name: Merge Pull request
        env:
          GITHUB_TOKEN: ${{ secrets.PULL_APPROVER }}
        run: gh pr merge test --repo "tim-grieve/CloudResumeWebsite" --merge